/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiYoutubeAuthRouteImport } from './routes/api/youtube/auth'
import { Route as ApiYoutubeBrainRouteImport } from './routes/api/youtube/brain'
import { Route as ApiYoutubeDisconnectRouteImport } from './routes/api/youtube/disconnect'
import { Route as ApiYoutubeRefreshRouteImport } from './routes/api/youtube/refresh'
import { Route as ApiYoutubeStatusRouteImport } from './routes/api/youtube/status'
import { Route as ApiYoutubeSyncRouteImport } from './routes/api/youtube/sync'
import { Route as ApiPublicYoutubeCallbackRouteImport } from './routes/api/public/youtube/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiYoutubeAuthRoute = ApiYoutubeAuthRouteImport.update({
  id: '/api/youtube/auth',
  path: '/api/youtube/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeBrainRoute = ApiYoutubeBrainRouteImport.update({
  id: '/api/youtube/brain',
  path: '/api/youtube/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeDisconnectRoute = ApiYoutubeDisconnectRouteImport.update({
  id: '/api/youtube/disconnect',
  path: '/api/youtube/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRefreshRoute = ApiYoutubeRefreshRouteImport.update({
  id: '/api/youtube/refresh',
  path: '/api/youtube/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeStatusRoute = ApiYoutubeStatusRouteImport.update({
  id: '/api/youtube/status',
  path: '/api/youtube/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeSyncRoute = ApiYoutubeSyncRouteImport.update({
  id: '/api/youtube/sync',
  path: '/api/youtube/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeCallbackRoute =
  ApiPublicYoutubeCallbackRouteImport.update({
    id: '/api/public/youtube/callback',
    path: '/api/public/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/youtube/auth': typeof ApiYoutubeAuthRoute
  '/api/youtube/brain': typeof ApiYoutubeBrainRoute
  '/api/youtube/disconnect': typeof ApiYoutubeDisconnectRoute
  '/api/youtube/refresh': typeof ApiYoutubeRefreshRoute
  '/api/youtube/status': typeof ApiYoutubeStatusRoute
  '/api/youtube/sync': typeof ApiYoutubeSyncRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/youtube/auth': typeof ApiYoutubeAuthRoute
  '/api/youtube/brain': typeof ApiYoutubeBrainRoute
  '/api/youtube/disconnect': typeof ApiYoutubeDisconnectRoute
  '/api/youtube/refresh': typeof ApiYoutubeRefreshRoute
  '/api/youtube/status': typeof ApiYoutubeStatusRoute
  '/api/youtube/sync': typeof ApiYoutubeSyncRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/youtube/auth': typeof ApiYoutubeAuthRoute
  '/api/youtube/brain': typeof ApiYoutubeBrainRoute
  '/api/youtube/disconnect': typeof ApiYoutubeDisconnectRoute
  '/api/youtube/refresh': typeof ApiYoutubeRefreshRoute
  '/api/youtube/status': typeof ApiYoutubeStatusRoute
  '/api/youtube/sync': typeof ApiYoutubeSyncRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/api/youtube/auth'
    | '/api/youtube/brain'
    | '/api/youtube/disconnect'
    | '/api/youtube/refresh'
    | '/api/youtube/status'
    | '/api/youtube/sync'
    | '/api/public/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/api/youtube/auth'
    | '/api/youtube/brain'
    | '/api/youtube/disconnect'
    | '/api/youtube/refresh'
    | '/api/youtube/status'
    | '/api/youtube/sync'
    | '/api/public/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/settings'
    | '/api/youtube/auth'
    | '/api/youtube/brain'
    | '/api/youtube/disconnect'
    | '/api/youtube/refresh'
    | '/api/youtube/status'
    | '/api/youtube/sync'
    | '/api/public/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiYoutubeAuthRoute: typeof ApiYoutubeAuthRoute
  ApiYoutubeBrainRoute: typeof ApiYoutubeBrainRoute
  ApiYoutubeDisconnectRoute: typeof ApiYoutubeDisconnectRoute
  ApiYoutubeRefreshRoute: typeof ApiYoutubeRefreshRoute
  ApiYoutubeStatusRoute: typeof ApiYoutubeStatusRoute
  ApiYoutubeSyncRoute: typeof ApiYoutubeSyncRoute
  ApiPublicYoutubeCallbackRoute: typeof ApiPublicYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/youtube/auth': {
      id: '/api/youtube/auth'
      path: '/api/youtube/auth'
      fullPath: '/api/youtube/auth'
      preLoaderRoute: typeof ApiYoutubeAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/brain': {
      id: '/api/youtube/brain'
      path: '/api/youtube/brain'
      fullPath: '/api/youtube/brain'
      preLoaderRoute: typeof ApiYoutubeBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/disconnect': {
      id: '/api/youtube/disconnect'
      path: '/api/youtube/disconnect'
      fullPath: '/api/youtube/disconnect'
      preLoaderRoute: typeof ApiYoutubeDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/refresh': {
      id: '/api/youtube/refresh'
      path: '/api/youtube/refresh'
      fullPath: '/api/youtube/refresh'
      preLoaderRoute: typeof ApiYoutubeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/status': {
      id: '/api/youtube/status'
      path: '/api/youtube/status'
      fullPath: '/api/youtube/status'
      preLoaderRoute: typeof ApiYoutubeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/sync': {
      id: '/api/youtube/sync'
      path: '/api/youtube/sync'
      fullPath: '/api/youtube/sync'
      preLoaderRoute: typeof ApiYoutubeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube/callback': {
      id: '/api/public/youtube/callback'
      path: '/api/public/youtube/callback'
      fullPath: '/api/public/youtube/callback'
      preLoaderRoute: typeof ApiPublicYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiYoutubeAuthRoute: ApiYoutubeAuthRoute,
  ApiYoutubeBrainRoute: ApiYoutubeBrainRoute,
  ApiYoutubeDisconnectRoute: ApiYoutubeDisconnectRoute,
  ApiYoutubeRefreshRoute: ApiYoutubeRefreshRoute,
  ApiYoutubeStatusRoute: ApiYoutubeStatusRoute,
  ApiYoutubeSyncRoute: ApiYoutubeSyncRoute,
  ApiPublicYoutubeCallbackRoute: ApiPublicYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
